---
- name: Setting up hw0 web server
  hosts: all
  become: true
  tasks:
     - name: Update apt-cache 
       apt: update_cache=yes

     - name: Install nginx
       apt: name=nginx state=latest

     - name: Open port 80
       ufw:
        rule: allow
        port: http

     - name: Reload firewall
       ufw:
        state: reloaded

     - name: Unlink original nginx config file
       file: 
        path: "/etc/nginx/sites-enabled/default"
        state: absent

     - name: Add new nginx config file
       template: 
        src: server.tpl
        dest: /etc/nginx/sites-available/anvelazquez.cse356.compas.cs.stonybrook.edu
       notify: restart nginx

     - name: Creating new webpage content directory
       file: 
        path: "/var/www/anvelazquez.cse356.compas.cs.stonybrook.edu"
        state: directory
        mode: '0755'

     - name: Enable new site config file
       command: "ln -s /etc/nginx/sites-available/anvelazquez.cse356.compas.cs.stonybrook.edu /etc/nginx/sites-enabled/"

     - name: Add hw0.html file to content directory
       copy: 
        src: hw0.html
        dest: /var/www/anvelazquez.cse356.compas.cs.stonybrook.edu/hw0.html
        mode: '0644'

     - name: Add pokemon.jpeg file to content directory
       copy: 
        src: pokemon.jpeg
        dest: /var/www/anvelazquez.cse356.compas.cs.stonybrook.edu/pokemon.jpeg
        mode: '0644'

  handlers:
     - name: restart nginx
       service: name=nginx state=restarted


    
